
package Webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "TestingWebserviceServerSoap", targetNamespace = "http://localhost/CimsService/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface TestingWebserviceServerSoap {


    /**
     * @param title
     * @param message
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "PublishEmergencyMessage", action = "http://localhost/CimsService/PublishEmergencyMessage")
    @WebResult(name = "PublishEmergencyMessageResult", targetNamespace = "http://localhost/CimsService/")
    @RequestWrapper(localName = "PublishEmergencyMessage", targetNamespace = "http://localhost/CimsService/", className = "Webservice.PublishEmergencyMessage")
    @ResponseWrapper(localName = "PublishEmergencyMessageResponse", targetNamespace = "http://localhost/CimsService/", className = "Webservice.PublishEmergencyMessageResponse")
    String publishEmergencyMessage(
            @WebParam(name = "title", targetNamespace = "http://localhost/CimsService/")
                    String title,
            @WebParam(name = "message", targetNamespace = "http://localhost/CimsService/")
                    String message);

}
